#!/bin/bash
# Written by Netkas 3/01/2021
echo "Intellivoid Provisioning"
echo "Running on x86_64 (docker) [PRODUCTION]"
echo " "
echo " ## Authentication Required "
read -p 'Enter your 25-50 character PAT: ' GIT_API_KEY


echo " #### Cloning CoffeeHousePy"
git clone https://${GIT_API_KEY}@github.com/Intellivoid/CoffeeHousePy.git
cd /CoffeeHousePy
git checkout corenlp

echo " #### Preparing System for Python"
make system_prep_python

echo " #### Preparing System for pip"
make system_prep_pip

echo " #### Preparing System for GCC"
make system_prep_gcc

echo " #### Preparing System for Java"
make system_prep_java

echo " #### Building and Installing CoffeeHousePy"
make install